#!/bin/bash

lankebuild_prepare() {
    # Prepare environment
    :
}

lankebuild_build() {
    mkdir build && cd build
    meson setup --prefix="{PREFIX}" --buildtype=release -D docs=false ..
    ninja -j$(nproc)
    DESTDIR="{STAGING_ROOT}" ninja install
}


lankebuild_package() {
    # Installation handled by builder
    :
}
