#!/bin/bash

lankebuild_prepare() {
    # Prepare environment
    :
}

lankebuild_build() {
    make prefix=/usr -j$(nproc)
    make prefix=/usr DESTDIR={STAGING_ROOT} install
    rm -f {STAGING_ROOT}{LIBDIR}/libzstd.a
    # 添加兼容性链接
    ln -sfv zstd {STAGING_ROOT}{BINDIR}/zstdcat
    ln -sfv zstd {STAGING_ROOT}{BINDIR}/unzstd
    ln -sfv zstd {STAGING_ROOT}{BINDIR}/zstdmt
}


lankebuild_package() {
    # Installation handled by builder
    :
}
