#!/bin/bash

lankebuild_prepare() {
    # Prepare environment
    :
}

lankebuild_build() {
    INC_DIR="{STAGING_ROOT}/usr/include/xcb"
    LIB_DIR="{STAGING_ROOT}/usr/lib"
    PC_DIR="$LIB_DIR/pkgconfig"
    mkdir -p "$INC_DIR" "$PC_DIR"

    # 1. 伪造头文件
    touch "$INC_DIR/xcb_util.h" "$INC_DIR/xcb_image.h" "$INC_DIR/xcb_keysyms.h"

    # 2. 伪造共享库 (让链接器闭嘴)
    gcc -shared -o "$LIB_DIR/libxcb-util.so.0.0.0" -Wl,-soname,libxcb-util.so.0 -x c /dev/null
    ln -s libxcb-util.so.0.0.0 "$LIB_DIR/libxcb-util.so.0"
    ln -s libxcb-util.so.0.0.0 "$LIB_DIR/libxcb-util.so"

    # 3. 伪造 pkg-config
    cat > "$PC_DIR/xcb-util.pc" <<'EOF'
prefix=/usr
libdir=$prefix/lib
includedir=$prefix/include
Name: xcb-util
Description: XCB stub for LankeOS
Version: 1.0
Libs: -L$libdir -lxcb-util
Cflags: -I$includedir
EOF
}


lankebuild_package() {
    # Installation handled by builder
    :
}
