#!/bin/bash

lankebuild_prepare() {
    :
}

lankebuild_build() {
    mkdir build && cd build
    meson setup .. --prefix=/usr --buildtype=release       --wrap-mode=nofallback       -Dx11-backend=false       -Dwayland-backend=true       -Dvulkan=disabled       -Dbuild-demos=false       -Dbuild-tests=false       -Dbuild-examples=false       -Dbuild-testsuite=false       -Ddocumentation=false       -Dman-pages=false       -Dmedia-gstreamer=disabled       -Dcloudproviders=disabled       -Dintrospection=disabled       -Dtracker=disabled       -Dcolord=disabled       -Dsysprof=disabled       -Dprint-cups=disabled       -Dprint-cpdb=disabled
    ninja -j$(nproc)
    DESTDIR={STAGING_ROOT} ninja install
}

lankebuild_package() {
    :
}
