#!/bin/bash

lankebuild_prepare() {
    # Prepare environment
    :
}

lankebuild_build() {
    mkdir build && cd build
    cmake .. -DCMAKE_INSTALL_PREFIX={PREFIX} -DENABLE_VULKAN=OFF -DENABLE_WAYLAND=OFF -DENABLE_DRM=OFF -DENABLE_GIO=OFF -DENABLE_DBUS=OFF -DCMAKE_INSTALL_SYSCONFDIR={SYSCONFDIR}
    make -j$(nproc)
    make DESTDIR={STAGING_ROOT} install
}


lankebuild_package() {
    # Installation handled by builder
    :
}
