#!/bin/sh
set -e

lankebuild_prepare() {
    echo "Preparing libgpg-error-1.54..."
}

lankebuild_build() {
    echo "Configuring libgpg-error-1.54..."
    ./configure --prefix={PREFIX} --sysconfdir={SYSCONFDIR}
    echo "Building libgpg-error-1.54..."
    make -j$(nproc)
    echo "Build complete."
}

lankebuild_package() {
    echo "Packaging libgpg-error-1.54..."
    make DESTDIR="{STAGING_ROOT}" install
    echo "Package staging complete."
}
