#!/bin/bash

lankebuild_prepare() {
    sed -r '/cmake_policy.*(0025|0054)/d' -i source/CMakeLists.txt
    # 使用自定义配置，启用共享库
    mkdir bld && cd bld && cmake -D CMAKE_INSTALL_PREFIX=/usr        \
      -D GIT_ARCHETYPE=1                  \
      -D CMAKE_POLICY_VERSION_MINIMUM=3.5 \
      -W no-dev                           \
      ../source
    cd ..
}

lankebuild_build() {
    cd bld
    make -j$(nproc)
    make DESTDIR={STAGING_ROOT} install
}

lankebuild_package() {
    rm -vf {STAGING_ROOT}/usr/lib/libx265.a
}
