#!/bin/bash

lankebuild_prepare() {
    :
}

lankebuild_build() {
    ./configure --prefix={PREFIX} --sysconfdir={SYSCONFDIR}
    make -j$(nproc)
    make DESTDIR={STAGING_ROOT} install
    # Remove static library from staging (shared lib kept)
    rm -f {STAGING_ROOT}{LIBDIR}/libz.a
}

lankebuild_package() {
    :
}
