#!/bin/bash

lankebuild_prepare() {
    # Prepare environment
    ./configure --prefix=/usr --sysconfdir=/etc
}

lankebuild_build() {
    make -j$(nproc)
}


lankebuild_package() {
    make DESTDIR="{STAGING_ROOT}" install
    rm "{STAGING_ROOT}/etc/profile.d/bash_completion.sh"
}
