#!/bin/bash

lankebuild_prepare() {
    # Prepare environment
    :
}

lankebuild_build() {
    meson setup build --prefix=/usr -Dman-pages=disabled
    DESTDIR={STAGING_ROOT} ninja -C build install

    # --- 加入 Systemd Unit 文件的逻辑 ---
    echo "=> 正在注入 seatd.service..."
    mkdir -p "{STAGING_ROOT}/usr/lib/systemd/system"
    cat > "{STAGING_ROOT}/usr/lib/systemd/system/seatd.service" <<EOF
[Unit]
Description=Seat management daemon
Documentation=man:seatd(1)
DefaultDependencies=no
Conflicts=shutdown.target
After=systemd-udev-settle.service
Before=shutdown.target multi-user.target display-manager.service

[Service]
Type=simple
ExecStart=/usr/bin/seatd -g video
Restart=always
RestartSec=1

[Install]
WantedBy=multi-user.target
EOF
    # ----------------------------------

}


lankebuild_package() {
    # Installation handled by builder
    :
}
