#!/bin/bash
lankebuild_prepare() {
    :
}
lankebuild_build() {
    # LSB-Tools 没有 configure 脚本，直接 make
    make -j$(nproc)
    make DESTDIR={STAGING_ROOT} install
    
    # 按照原逻辑创建符号链接
    ln -sfv ../lib/lsb/install_initd {STAGING_ROOT}{BINDIR}/install_initd
    ln -sfv ../lib/lsb/remove_initd {STAGING_ROOT}{BINDIR}/remove_initd
    ln -sfv ../lib/lsb/lsbinstall {STAGING_ROOT}{BINDIR}/lsbinstall
}
lankebuild_package() {
    :
}
