#!/bin/bash

lankebuild_prepare() {
    # Prepare environment
    :
}

lankebuild_build() {
    meson setup build --prefix=/usr --buildtype=release -Denable-x11=false
    ninja -C build
    DESTDIR={STAGING_ROOT} ninja -C build install
}


lankebuild_package() {
    # Installation handled by builder
    :
}
