#!/bin/bash

lankebuild_prepare() {
    :
}

lankebuild_build() {
    cargo build --release --locked
    install -vDm 755 target/release/starship {STAGING_ROOT}{BINDIR}/starship
}

lankebuild_package() {
    mkdir -p "{STAGING_ROOT}/usr/share/fish/vendor_conf.d/"
    cat > "{STAGING_ROOT}/usr/share/fish/vendor_conf.d/starship.fish" << 'EOF'
if type -q starship
    starship init fish | source
end
EOF
}
