#!/bin/bash

lankebuild_prepare() {
    :
}

lankebuild_build() {
    cargo build --release --locked
    install -vDm 755 target/release/starship {STAGING_ROOT}{BINDIR}/starship
}

lankebuild_package() {
    :
}
