#!/bin/bash

lankebuild_prepare() {
    # Prepare environment
    :
}

lankebuild_build() {
    ./configure --prefix={PREFIX} --sysconfdir={SYSCONFDIR} --without-bash-malloc --with-installed-readline --disable-static --disable-doc
    make -j$(nproc)
    make DESTDIR={STAGING_ROOT} install
    ln -sf bash {STAGING_ROOT}{BINDIR}/sh
}


lankebuild_package() {
    # Installation handled by builder
    :
}
