#!/bin/bash

lankebuild_prepare() {
    :
}

lankebuild_build() {
    ./configure \
        --prefix={PREFIX} \
        --localstatedir={LOCALSTATEDIR} \
        --target-list=x86_64-softmmu \
        --audio-drv-list=alsa,pipewire
    make -j$(nproc)
    make DESTDIR={STAGING_ROOT} install
}

lankebuild_package() {
    :
}
