#!/bin/bash

lankebuild_prepare() {
    # Prepare environment
    :
}

lankebuild_build() {
    echo '#define SYS_VIMRC_FILE "/etc/vimrc"' >> src/feature.h
    ./configure --prefix={PREFIX} --sysconfdir={SYSCONFDIR}
    make -j$(nproc)
    make DESTDIR={STAGING_ROOT} install
    ln -sf vim {STAGING_ROOT}{BINDIR}/vi
    ln -sfv vim {STAGING_ROOT}{BINDIR}/vimdiff
    ln -sfv vim {STAGING_ROOT}{BINDIR}/view
    ln -sfv vim {STAGING_ROOT}{BINDIR}/rvim
    ln -sfv vim {STAGING_ROOT}{BINDIR}/rview
    ln -sfv vim {STAGING_ROOT}{BINDIR}/ex
}



lankebuild_package() {
    # Installation handled by builder
    :
}
