#!/bin/bash

lankebuild_prepare() {
    # Prepare environment
    :
}

lankebuild_build() {
    mkdir build && cd build
    ../configure --prefix={PREFIX} --sysconfdir={SYSCONFDIR} --enable-shared --enable-threads=posix --enable-__cxa_atexit --enable-clocale=gnu --enable-languages=c,c++ --disable-multilib --disable-bootstrap --with-system-zlib -disable-static
    make -j$(nproc)
    make DESTDIR={STAGING_ROOT} install
    ln -sfv gcc {STAGING_ROOT}{BINDIR}/cc
    ln -sfv ../bin/cpp "{STAGING_ROOT}{LIBDIR}/cpp"
    mkdir -pv "{STAGING_ROOT}{LIBDIR}/bfd-plugins"
    ln -sfv ../../libexec/gcc/x86_64-pc-linux-gnu/16.1.0/liblto_plugin.so            "{STAGING_ROOT}{LIBDIR}/bfd-plugins/liblto_plugin.so"
}


lankebuild_package() {
    # Installation handled by builder
    :
}
