#!/bin/bash

lankebuild_prepare() {
    # Prepare environment
    :
}

lankebuild_build() {
    mkdir build && cd build
    cmake .. -G Ninja -DCMAKE_INSTALL_PREFIX=/usr -DBUILD_EXTERNAL=OFF -DALLOW_EXTERNAL_SPIRV_TOOLS=ON -DCMAKE_BUILD_TYPE=Release
    DESTDIR={STAGING_ROOT} ninja install
}


lankebuild_package() {
    # Installation handled by builder
    :
}
