#!/bin/bash

lankebuild_prepare() {
    # Prepare environment
    :
}

lankebuild_build() {
    mkdir build && cd build
    cmake .. -DCMAKE_INSTALL_SYSCONFDIR={SYSCONFDIR} -G Ninja -DCMAKE_INSTALL_PREFIX={PREFIX} -DBUILD_EXTERNAL=OFF -DALLOW_EXTERNAL_SPIRV_TOOLS=ON -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=ON
    DESTDIR={STAGING_ROOT} ninja install
}


lankebuild_package() {
    # Installation handled by builder
    :
}
