#!/bin/bash

lankebuild_prepare() {
    # Prepare environment
    :
}

lankebuild_build() {
    mkdir build && cd build
    meson setup .. --prefix={PREFIX} --sysconfdir={SYSCONFDIR} --buildtype=release -Ddefault_library=shared -Ddefault-dnssec=no -Dfirstboot=false -Dman=disabled -Dpam=enabled -Dlogind=true -Dmode=release -Dwerror=false
    ninja -j$(nproc)
    DESTDIR={STAGING_ROOT} ninja install

    # 添加系统管理链接
    for tool in reboot halt poweroff shutdown telinit runlevel; do
        ln -sfv systemctl {STAGING_ROOT}{BINDIR}/$tool
    done
    ln -sfv resolvectl {STAGING_ROOT}{BINDIR}/systemd-resolve
    ln -sfv resolvectl {STAGING_ROOT}{BINDIR}/resolvconf
    ln -sfv ../lib/systemd/systemd {STAGING_ROOT}{BINDIR}/init
    ln -sfv systemd-run {STAGING_ROOT}{BINDIR}/run0
    ln -sfv systemd-sysext {STAGING_ROOT}{BINDIR}/systemd-confext
    ln -sfv systemd-mount {STAGING_ROOT}{BINDIR}/systemd-umount
    ln -sfv udevadm {STAGING_ROOT}{BINDIR}/udevd

    # 建立 LankeOS 默认预设策略：禁用自带网络管理，优先使用 NetworkManager
    mkdir -pv {STAGING_ROOT}{LIBDIR}/systemd/system-preset
    cat > {STAGING_ROOT}{LIBDIR}/systemd/system-preset/99-lankeos.preset << "EOF"
disable systemd-networkd.service
disable systemd-resolved.service
enable NetworkManager.service
enable sshd.service
EOF

    echo "systemd-machine-id-setup" >> "{STAGING_HOOKS}/postinst.sh"
    echo "systemctl preset-all" >> "{STAGING_HOOKS}/postinst.sh"
}


lankebuild_package() {
    # Installation handled by builder
    :
}
