#!/bin/bash

lankebuild_prepare() {
    # Prepare environment
    :
}

lankebuild_build() {
    mkdir -p {STAGING_ROOT}/etc
    cp services protocols {STAGING_ROOT}/etc/
}


lankebuild_package() {
    # Installation handled by builder
    :
}
