#!/bin/bash
lankebuild_prepare() { :; }

lankebuild_build() {
    ./configure --prefix=/usr     \
                --sysconfdir=/etc \
                --disable-static
    make
    make DESTDIR={STAGING_ROOT} install
}

lankebuild_package() { :; }
