#!/bin/bash

lankebuild_prepare() {
    # Prepare environment
    :
}

lankebuild_build() {
    mkdir build && cd build
    meson setup .. --prefix={PREFIX} --sysconfdir={SYSCONFDIR} --buildtype=release \
      -Dintrospection=enabled \
      -Ddoc=disabled \
      -Dsystemd=enabled \
      -Dsystemd-user-service=true \
      -Dsystemd-system-service=false \
      -Dsystem-lua=true
    ninja -j$(nproc)
    DESTDIR={STAGING_ROOT} ninja install
}

lankebuild_package() {
    # Installation handled by builder
    :
}
