#!/bin/bash

lankebuild_prepare() {
    CFLAGS="-std=gnu99" ./configure --prefix={PREFIX} --sysconfdir={SYSCONFDIR} --disable-static
}

lankebuild_build() {
    make -j$(nproc)
    make DESTDIR={STAGING_ROOT} install
}

lankebuild_package() {
    :
}
