#!/bin/bash

lankebuild_prepare() {
    :
}

lankebuild_build() {
    mkdir build && cd build
    meson setup .. --prefix={PREFIX} --sysconfdir={SYSCONFDIR} --buildtype=release -Dglx=yes -Degl=yes
    ninja -j$(nproc)
    DESTDIR={STAGING_ROOT} ninja install
}

lankebuild_package() {
    :
}
