#!/bin/bash

lankebuild_prepare() {
    # Prepare environment
    autoreconf -i
    ./configure --prefix=/usr
}

lankebuild_build() {
    make -j$(nproc)
}


lankebuild_package() {
    make DESTDIR="{STAGING_ROOT}" install
}
