#!/bin/bash

lankebuild_prepare() {
    :
}

lankebuild_build() {
    meson setup build \
        --prefix={PREFIX} \
        --buildtype=release \
        -Ddefault_library=shared
    ninja -C build
    DESTDIR={STAGING_ROOT} ninja -C build install
}

lankebuild_package() {
    :
}
