#!/bin/bash

lankebuild_prepare() {
    # Prepare environment
    :
}

lankebuild_build() {
    meson setup build --prefix={PREFIX} --sysconfdir={SYSCONFDIR}
    ninja -C build -j$(nproc)
    DESTDIR={STAGING_ROOT} ninja -C build install
}


lankebuild_package() {
    # Installation handled by builder
    :
}
