#!/bin/bash

lankebuild_prepare() {
    # Prepare environment
    :
}

lankebuild_build() {
    mkdir build && cd build
    ../configure --prefix=/usr --sysconfdir=/etc --enable-elf-shlibs --disable-static --disable-libblkid --disable-libuuid --disable-fsck
    make -j$(nproc)
    make DESTDIR={STAGING_ROOT} install
    find {STAGING_ROOT}/usr/lib -name "*.a" -delete
}


lankebuild_package() {
    # Installation handled by builder
    :
}
