#!/bin/bash

lankebuild_prepare() {
    # Prepare environment
    :
}

lankebuild_build() {
    git clone --depth 1 --branch 1.1.10 https://github.com/fcitx/libime
    cd libime
    git submodule update --init --recursive

    cmake -G Ninja -B build \
        -DCMAKE_INSTALL_PREFIX={PREFIX} \
        -DCMAKE_INSTALL_SYSCONFDIR={SYSCONFDIR} \
        -DCMAKE_BUILD_TYPE=Release \
        -DENABLE_TEST=OFF \
        -DCMAKE_CXX_FLAGS='-w'

    ninja -C build -j$(nproc)
    DESTDIR={STAGING_ROOT} ninja -C build install
}


lankebuild_package() {
    # Installation handled by builder
    :
}
