#!/bin/bash

lankebuild_prepare() {
    # Prepare environment
    :
}

lankebuild_build() {
    # Enable GX/AAT, OpenType validation, and Subpixel Rendering
    sed -ri 's:.*(AUX_MODULES.*valid):\1:' modules.cfg
    sed -r 's:.*(#.*SUBPIXEL_RENDERING) .*:\1:' -i include/freetype/config/ftoption.h

    ./configure --prefix=/usr --enable-freetype-config --disable-static
    make
    make DESTDIR={STAGING_ROOT} install
}


lankebuild_package() {
    # Installation handled by builder
    :
}
