#!/bin/bash

lankebuild_prepare() {
    # Prepare environment
    :
}

lankebuild_build() {
    make linux
    make INSTALL_TOP={STAGING_ROOT}/usr install
    mkdir -p '{STAGING_ROOT}/usr/lib/pkgconfig'
    cat > '{STAGING_ROOT}/usr/lib/pkgconfig/lua.pc' << 'EOF'
V=5.5
R=5.5.0
prefix=/usr
INSTALL_BIN=\$prefix/bin
INSTALL_INC=\$prefix/include
INSTALL_LIB=\$prefix/lib
exec_prefix=\$prefix
libdir=\$exec_prefix/lib
includedir=\$prefix/include

Name: Lua
Description: An Extensible Extension Language
Version: \$R
Requires:
Libs: -L\$libdir -llua -lm -ldl
Cflags: -I\$includedir
EOF
}


lankebuild_package() {
    # Installation handled by builder
    :
}
