#!/bin/bash

lankebuild_prepare() {
    # Prepare environment
    :
}

lankebuild_build() {
    mkdir build && cd build
    cmake -D CMAKE_INSTALL_PREFIX=/usr -D CMAKE_BUILD_TYPE=Release -D SPIRV_WERROR=OFF -D BUILD_SHARED_LIBS=ON -D SPIRV_TOOLS_BUILD_STATIC=OFF -D SPIRV-Headers_SOURCE_DIR=/usr -G Ninja ..
    DESTDIR={STAGING_ROOT} ninja install
    mkdir -p "{STAGING_ROOT}/usr/lib/pkgconfig"
    cat > "{STAGING_ROOT}/usr/lib/pkgconfig/SPIRV-Tools.pc" << EOF
prefix=/usr
libdir=\$prefix/lib
includedir=\$prefix/include
Name: SPIRV-Tools
Version: 2026.1
Libs: -L\$libdir -lSPIRV-Tools -lSPIRV-Tools-shared
Cflags: -I\$includedir
EOF
    cp "{STAGING_ROOT}/usr/lib/pkgconfig/SPIRV-Tools.pc" "{STAGING_ROOT}/usr/lib/pkgconfig/SPIRV-Tools-shared.pc"
}


lankebuild_package() {
    # Installation handled by builder
    :
}
