#!/bin/bash

lankebuild_prepare() {
    # Prepare environment
    :
}

lankebuild_build() {
    ./configure --prefix={PREFIX} --sysconfdir={SYSCONFDIR} --disable-static --disable-doc
    make -j$(nproc)
    make DESTDIR={STAGING_ROOT} install
    # 添加兼容性链接
    for tool in xzcat unxz lzma unlzma lzcat; do
        ln -sfv xz {STAGING_ROOT}{BINDIR}/$tool
    done
    ln -sfv xzgrep {STAGING_ROOT}{BINDIR}/lzgrep
    ln -sfv xzgrep {STAGING_ROOT}{BINDIR}/lzegrep
    ln -sfv xzgrep {STAGING_ROOT}{BINDIR}/lzfgrep
    ln -sfv xzgrep {STAGING_ROOT}{BINDIR}/xzegrep
    ln -sfv xzgrep {STAGING_ROOT}{BINDIR}/xzfgrep
    ln -sfv xzdiff {STAGING_ROOT}{BINDIR}/lzdiff
    ln -sfv xzdiff {STAGING_ROOT}{BINDIR}/lzcmp
    ln -sfv xzdiff {STAGING_ROOT}{BINDIR}/xzcmp
    ln -sfv xzless {STAGING_ROOT}{BINDIR}/lzless
    ln -sfv xzmore {STAGING_ROOT}{BINDIR}/lzmore
}


lankebuild_package() {
    # Installation handled by builder
    :
}
