#!/bin/bash

lankebuild_prepare() {
    # Prepare environment
    :
}

lankebuild_build() {
    mkdir build && cd build
    cmake -G Ninja .. \
        -DCMAKE_INSTALL_PREFIX=/usr \
        -DCMAKE_BUILD_TYPE=Release \
        -DCMAKE_INSTALL_LIBDIR=lib \
        -DENABLE_GTK2_IM_MODULE=OFF \
        -DENABLE_GTK3_IM_MODULE=ON \
        -DENABLE_GTK4_IM_MODULE=OFF \
        -DENABLE_SNOOPER=ON \
        -DENABLE_GIR=OFF
    DESTDIR={STAGING_ROOT} ninja install
}


lankebuild_package() {
    # Installation handled by builder
    mkdir -p "{STAGING_ROOT}/etc/profile.d"
    cat > "{STAGING_ROOT}/etc/profile.d/fcitx5-gtk.sh" << 'EOF'
#!/bin/bash
# start of fcitx5-gtk
export GTK_IM_MODULE=fcitx
# end of fcitx5-gtk
EOF
}
