#!/bin/bash

lankebuild_prepare() {
    :
}

lankebuild_build() {
    # librsvg 2.60.x: meson build with Rust component via cargo-c
    # --disable-static: no static libs
    meson setup build \
        --prefix={PREFIX} \
        --buildtype=release \
        -Ddefault_library=shared \
        -Dtests=false \
        -Ddocs=disabled \
        -Dintrospection=enabled \
        -Dvala=disabled
    ninja -C build
    DESTDIR={STAGING_ROOT} ninja -C build install
}

lankebuild_package() {
    :
}
