#!/bin/bash

lankebuild_prepare() {
    make install PREFIX=/usr DESTDIR="{STAGING_ROOT}"
}

lankebuild_build() {
    # Headers only, no compilation needed
    :
}


lankebuild_package() {
    # Done in prepare
    :
}
