#!/bin/bash

lankebuild_prepare() {
    # Prepare environment
    :
}

lankebuild_build() {
    mkdir build && cd build
    meson setup .. --prefix=/usr --buildtype=release -Dsession-managers=[] -Draop=disabled -Dbluez5=disabled -Dman=disabled -Ddocs=disabled -Dtests=disabled -Dpipewire-v4l2=disabled -Dpipewire-jack=enabled -Dpipewire-alsa=enabled -Dspa-plugins=enabled -Dlibsystemd=enabled -Dlogind=enabled -Dsystemd-user-service=enabled -Dc_args=\"-Wno-error=unused-result\"
    ninja -j$(nproc)
    DESTDIR={STAGING_ROOT} ninja install
}


lankebuild_package() {
    # Installation handled by builder
    :
}
