#!/bin/bash

lankebuild_prepare() {
    :
}

lankebuild_build() {
    mkdir build && cd build
    cmake -D CMAKE_INSTALL_PREFIX=/usr -G Ninja ..
    ninja
    DESTDIR={STAGING_ROOT} ninja install
}

lankebuild_package() {
    :
}
