#!/bin/bash

lankebuild_prepare() {
    # Prepare environment
    :
}

lankebuild_build() {
    for dir in */; do
        if [ -d "$dir" ]; then
            cd "$dir"
            break
        fi
    done
    patch -Np1 -i {WORK_DIR}/kbd-2.8.0-backspace-1.patch
    sed -i '/RESIZECONS_PROGS=/s/yes/no/' configure
    sed -i 's/resizecons.8 //' docs/man/man8/Makefile.in
    ./configure --prefix={PREFIX} --sysconfdir={SYSCONFDIR} --disable-static --disable-vlock
    make -j$(nproc)
    make DESTDIR={STAGING_ROOT} install
    # 添加 psf 工具链接
    for tool in psfaddtable psfgettable psfstriptable; do
        ln -sfv psfxtable {STAGING_ROOT}{BINDIR}/$tool
    done
}


lankebuild_package() {
    # Installation handled by builder
    :
}
