#!/bin/bash

lankebuild_prepare() {
    grep -rl '^#!.*python$' | xargs sed -i '1s/python/&3/'
}

lankebuild_build() {
    mkdir -v build
    cd       build

    cmake -G "Unix Makefiles"          \
      -D CMAKE_BUILD_TYPE=Release  \
      -D CMAKE_INSTALL_PREFIX={PREFIX} \
      -DCMAKE_INSTALL_SYSCONFDIR={SYSCONFDIR} \
      -D build_wizard=OFF          \
      -W no-dev ..

    make -j$(nproc)
}

lankebuild_package() {
    cd build && make DESTDIR={STAGING_ROOT} install
}
