#!/bin/bash

lankebuild_prepare() {
    cd snowball-3.1.1
    patch -p1 < "{WORK_DIR}"/0001-Make-libstemmer-a-shared-library.patch
    # Prepare environment
}

lankebuild_build() {
    cd snowball-3.1.1
    make -j$(nproc)
}


lankebuild_package() {
    cd snowball-3.1.1
    install -Dm644 include/libstemmer.h -t "{STAGING_ROOT}/usr/include"
    install -Dm644 libstemmer.so.0 "{STAGING_ROOT}/usr/lib/libstemmer.so.0.0.0"
    ln -s libstemmer.so.0.0.0 "{STAGING_ROOT}/usr/lib/libstemmer.so.0"
    ln -s libstemmer.so.0 "{STAGING_ROOT}/usr/lib/libstemmer.so"
    install -Dm644 COPYING -t "{STAGING_ROOT}/usr/share/licenses/libstemmer/"
}
