#!/bin/bash

lankebuild_prepare() {
    :
}

lankebuild_build() {
    mkdir build && cd build
    cmake -D CMAKE_INSTALL_PREFIX={PREFIX} \
    -DCMAKE_INSTALL_SYSCONFDIR={SYSCONFDIR} \
          -D CMAKE_BUILD_TYPE=Release \
          -D BUILD_SHARED_LIBS=ON \
          -D CMAKE_SKIP_INSTALL_RPATH=ON \
          -D LLVM_EXTERNAL_SPIRV_HEADERS_SOURCE_DIR=/usr \
          -G Ninja ..
    ninja
    DESTDIR={STAGING_ROOT} ninja install
}

lankebuild_package() {
    :
}
