#!/bin/bash

lankebuild_prepare() {
    # Prepare environment
    :
}

lankebuild_build() {
    mkdir build && cd build
    cmake .. -G Ninja -DCMAKE_INSTALL_PREFIX=/usr -DLLVM_DIR=$(llvm-config --cmakedir)
    DESTDIR={STAGING_ROOT} ninja install
}


lankebuild_package() {
    # Installation handled by builder
    :
}
