#!/bin/bash

lankebuild_prepare() {
    ./configure --prefix={PREFIX} --sysconfdir={SYSCONFDIR} \
                --enable-shared \
                --disable-static
}

lankebuild_build() {
    make -j$(nproc)
    make DESTDIR={STAGING_ROOT} install
}

lankebuild_package() {
    :
}
