#!/bin/bash

lankebuild_prepare() {
    # Prepare environment
    :
}

lankebuild_build() {
    ./configure --prefix={PREFIX} --sysconfdir={SYSCONFDIR} --disable-static
    make -j$(nproc)
    make DESTDIR={STAGING_ROOT} install
    ln -sfv gawk {STAGING_ROOT}{BINDIR}/awk
}


lankebuild_package() {
    # Installation handled by builder
    :
}
