#!/bin/bash

lankebuild_prepare() {
    # Prepare environment
    :
}

lankebuild_build() {
    mkdir build && cd build
    ../configure --prefix={PREFIX} --sysconfdir={SYSCONFDIR} --enable-gold --enable-ld=default --enable-plugins --enable-shared --disable-werror --with-system-zlib --enable-64-bit-bfd --disable-static
    make tooldir=/usr -j$(nproc)
    make tooldir=/usr DESTDIR={STAGING_ROOT} install
}


lankebuild_package() {
    # Installation handled by builder
    :
}
