#!/bin/bash

lankebuild_prepare() {
    :
}

lankebuild_build() {
    for dir in */; do
        if [ -d "$dir" ]; then
            cd "$dir"
            break
        fi
    done
    patch -Np1 -i {WORK_DIR}/bzip2-1.0.8-install_docs-1.patch

    cat > bzip2.pc <<EOF
prefix=/usr
exec_prefix=/usr
bindir=\${exec_prefix}/bin
libdir=\${exec_prefix}/lib
includedir=\${prefix}/include

Name: bzip2
Description: A file compression library
Version: 1.0.8
Libs: -L\${libdir} -lbz2
Cflags: -I\${includedir}
EOF
    make -f Makefile-libbz2_so -j$(nproc)
    make bzip2 bzip2recover -j$(nproc)
}

lankebuild_package() {
    cd bzip2-1.0.8

    install -dm755 {STAGING_ROOT}/usr/{bin,lib,include,share/man/man1}

    install -m755 bzip2-shared {STAGING_ROOT}/usr/bin/bzip2
    install -m755 bzip2recover bzdiff bzgrep bzmore {STAGING_ROOT}/usr/bin/
    ln -sf bzip2 {STAGING_ROOT}/usr/bin/bunzip2
    ln -sf bzip2 {STAGING_ROOT}/usr/bin/bzcat

    cp -a libbz2.so* {STAGING_ROOT}/usr/lib/
    ln -sf libbz2.so.1.0.8 {STAGING_ROOT}/usr/lib/libbz2.so.1
    ln -sf libbz2.so.1 {STAGING_ROOT}/usr/lib/libbz2.so

    install -m644 bzlib.h {STAGING_ROOT}/usr/include/

    install -m644 bzip2.1 {STAGING_ROOT}/usr/share/man/man1/
    ln -sf bzip2.1 {STAGING_ROOT}/usr/share/man/man1/bunzip2.1
    ln -sf bzip2.1 {STAGING_ROOT}/usr/share/man/man1/bzcat.1
    ln -sf bzip2.1 {STAGING_ROOT}/usr/share/man/man1/bzip2recover.1

    install -Dm644 bzip2.pc {STAGING_ROOT}/usr/lib/pkgconfig/bzip2.pc

    install -Dm644 LICENSE {STAGING_ROOT}/usr/share/licenses/bzip2/LICENSE
}

