#!/bin/bash

lankebuild_prepare() {
    # Prepare environment
    cargo fetch --locked --target host-tuple
}

lankebuild_build() {
    cargo build --frozen --release
}


lankebuild_package() {
    install -Dm755 "target/release/bat" "{STAGING_ROOT}/usr/bin/bat"

    # Package licenses
    install -Dm644 -t "{STAGING_ROOT}/usr/share/licenses/bat/" LICENSE-APACHE LICENSE-MIT

    cd target/release/build

    # Find and package the man page (because cargo --out-dir is too new)
    find . -name bat.1 -type f -exec install -Dm644 {} \
        "{STAGING_ROOT}/usr/share/man/man1/bat.1" \;

    # Find and package the bash completion file
    find . -name bat.bash -type f -exec install -Dm644 {} \
        "{STAGING_ROOT}/usr/share/bash-completion/completions/bat" \;

    # Find and package the zsh completion file (not in zsh-completions yet)
    find . -name bat.zsh -type f -exec install -Dm644 {} \
        "{STAGING_ROOT}/usr/share/zsh/site-functions/_bat" \;

    # Find and package the fish completion file
    find . -name bat.fish -type f -exec install -Dm644 {} \
        "{STAGING_ROOT}/usr/share/fish/vendor_completions.d/bat.fish" \;
}
