#!/bin/bash

lankebuild_prepare() {
    :
}

lankebuild_build() {
    mkdir build && cd build
    cmake -G Ninja .. \
        -DCMAKE_INSTALL_PREFIX={PREFIX} \
        -DCMAKE_INSTALL_SYSCONFDIR={SYSCONFDIR} \
        -DCMAKE_BUILD_TYPE=Release \
        -DFISH_USE_SYSTEM_PCRE2=ON \
        -DWITH_DOCS=OFF
    ninja
    DESTDIR={STAGING_ROOT} ninja install
}

lankebuild_package() {
    :
}
