#!/bin/bash
lankebuild_prepare() {
    :
}
lankebuild_build() {
    ./configure --prefix={PREFIX} --sysconfdir={SYSCONFDIR} --disable-static --with-curl --with-openssl --without-tcltk
    make -j$(nproc)
    make DESTDIR={STAGING_ROOT} install
}
lankebuild_package() {
    :
}
