#!/bin/bash
lankebuild_prepare() { :; }
lankebuild_build() {
    ./configure --prefix=/usr --disable-static --with-curl --with-openssl --without-tcltk
    make
    make DESTDIR={STAGING_ROOT} install
}
lankebuild_package() { :; }
