#!/bin/bash

lankebuild_prepare() {
    # Prepare environment
    :
}

lankebuild_build() {
    ./configure --prefix=/usr --disable-static --disable-doc
    make
    make DESTDIR={STAGING_ROOT} install
    ln -sfv pkgconf {STAGING_ROOT}/usr/bin/pkg-config
}


lankebuild_package() {
    # Installation handled by builder
    :
}
