#!/bin/bash

lankebuild_prepare() {
    :
}

lankebuild_build() {
    ./configure --prefix={PREFIX} --sysconfdir={SYSCONFDIR} --disable-static --disable-tools --disable-contrib --disable-webp
    make -j$(nproc)
    make DESTDIR={STAGING_ROOT} install
}

lankebuild_package() {
    :
}
