#!/bin/bash

lankebuild_prepare() {
    # Prepare environment
    :
}

lankebuild_build() {
    ./configure --prefix={PREFIX} --sysconfdir={SYSCONFDIR} --disable-static
    make -j$(nproc)
    make DESTDIR={STAGING_ROOT} install
    # 添加 pstree.x11 链接
    ln -sfv pstree {STAGING_ROOT}{BINDIR}/pstree.x11
}


lankebuild_package() {
    # Installation handled by builder
    :
}
