#!/bin/bash

lankebuild_prepare() {
    # Prepare environment
    :
}

lankebuild_build() {
    sh Configure -des -Dprefix={PREFIX} -Dvendorprefix={PREFIX} -Dprivlib={LIBDIR}/perl5/5.42/core_perl -Darchlib={LIBDIR}/perl5/5.42/core_perl -Dsitelib={LIBDIR}/perl5/5.42/site_perl -Dsitearch={LIBDIR}/perl5/5.42/site_perl -Dvendorlib={LIBDIR}/perl5/5.42/vendor_perl -Dvendorarch={LIBDIR}/perl5/5.42/vendor_perl
    make -j$(nproc)
    make DESTDIR={STAGING_ROOT} install
}


lankebuild_package() {
    # Installation handled by builder
    :
}
