#!/bin/bash

lankebuild_prepare() {
    # Prepare environment
    :
}

lankebuild_build() {
    sed -i '/MV.*old/d' Makefile.in
    sed -i '/$OLDSUFF/c:' support/shlib-install
    sed -i 's/-Wl,-rpath,[^ ]*//' support/shobj-conf
    sed -e '270a\     else\       chars_avail = 1;' -e '288i\   result = -1;' -i.orig input.c
    ./configure --prefix={PREFIX} --sysconfdir={SYSCONFDIR} --with-curses --disable-static --disable-doc
    make SHLIB_LIBS="-lncursesw" -j$(nproc)
    make DESTDIR={STAGING_ROOT} install
}


lankebuild_package() {
    # Installation handled by builder
    :
}
