#!/bin/bash

lankebuild_prepare() {
    # Prepare environment
    :
}

lankebuild_build() {
    ./configure --prefix=/usr --disable-static
    make -j$(nproc)
}


lankebuild_package() {
    make DESTDIR="{STAGING_ROOT}" prefix=/usr install
    install -Dm644 COPYING "{STAGING_ROOT}/usr/share/licenses/jq/COPYING"
}
