#!/bin/bash

lankebuild_prepare() {
    # Prepare environment
    :
}

lankebuild_build() {
    # LFS 安全性修复：移除可能破坏引导程序的优化标志
    unset {C,CPP,CXX,LD}FLAGS
    # 补充源码包发布时缺失的文件
    sed 's/--image-base/--nonexist-linker-option/' -i configure

    # 仅构建 UEFI 版本，移除 Legacy BIOS 支持
    ./configure --prefix=/usr --sysconfdir=/etc --disable-werror --disable-efiemu --with-platform=efi --target=x86_64 --enable-grub-mkfont
    make -j$(nproc)
    make DESTDIR={STAGING_ROOT} install
    find "{STAGING_ROOT}/usr/bin" -type f -exec sh -c 'for f; do if file "$f" | grep -q "ELF.*executable"; then strip "$f"; fi; done' _ {} +
}


lankebuild_package() {
    # Installation handled by builder
    :
}
