#!/bin/bash

lankebuild_prepare() {
    # Prepare environment
    :
}

lankebuild_build() {
    ./configure --prefix={PREFIX} --sysconfdir={SYSCONFDIR} --disable-static --disable-debuginfod --enable-libdebuginfod=dummy
    make -C lib -j$(nproc)
    make -C libelf -j$(nproc)
    make -C libelf install DESTDIR={STAGING_ROOT}
    mkdir -p {STAGING_ROOT}{LIBDIR}/pkgconfig
    install -vm644 config/libelf.pc {STAGING_ROOT}{LIBDIR}/pkgconfig
}


lankebuild_package() {
    # Installation handled by builder
    :
}
