#!/bin/bash

lankebuild_prepare() {
    # Prepare environment
    :
}

lankebuild_build() {
    # OpenSSL 不支持 no-static，手动安装后删除
    ./config --prefix={PREFIX} --openssldir=/etc/ssl --libdir=lib shared zlib-dynamic
    make -j$(nproc)
    make DESTDIR={STAGING_ROOT} install
    # 手动清理静态库以减小体积
    rm -f {STAGING_ROOT}{LIBDIR}/*.a
}


lankebuild_package() {
    # Installation handled by builder
    :
}
