#!/bin/bash

lankebuild_prepare() {
    # Prepare environment
    :
}

lankebuild_build() {
    mkdir build && cd build
    cmake .. -DCMAKE_INSTALL_SYSCONFDIR={SYSCONFDIR} -G Ninja -DCMAKE_INSTALL_PREFIX={PREFIX} -DENABLE_STATIC=FALSE
    DESTDIR={STAGING_ROOT} ninja install
}


lankebuild_package() {
    # Installation handled by builder
    :
}
