#!/bin/bash

lankebuild_prepare() {
    meson setup _build --prefix=/usr --buildtype=release \
        -Dtests=false
}

lankebuild_build() {
    meson compile -C _build -j$(nproc)
}


lankebuild_package() {
    DESTDIR="{STAGING_ROOT}" meson install -C _build
}
