#!/bin/bash

lankebuild_prepare() {
    # Prepare environment
    :
}

lankebuild_build() {
    CC=gcc CFLAGS="$CFLAGS -std=gnu11" ./configure --prefix=/usr -G -r
    make -j$(nproc)
    make DESTDIR={STAGING_ROOT} install
    ln -sfv bc {STAGING_ROOT}/usr/bin/dc
}


lankebuild_package() {
    # Installation handled by builder
    :
}
