#!/bin/bash

lankebuild_prepare() {
    # Prepare environment
    :
}

lankebuild_build() {
    CC=gcc CFLAGS="$CFLAGS -std=gnu11" ./configure --prefix={PREFIX} --sysconfdir={SYSCONFDIR} -G -r
    make -j$(nproc)
    make DESTDIR={STAGING_ROOT} install
    ln -sfv bc {STAGING_ROOT}{BINDIR}/dc
}


lankebuild_package() {
    # Installation handled by builder
    :
}
