#!/bin/bash

lankebuild_prepare() {
    sed '/build-version/d'   -i glslc/CMakeLists.txt            &&
    sed '/third_party/d'     -i CMakeLists.txt                  &&
    sed 's|SPIRV|glslang/&|' -i libshaderc_util/src/compiler.cc &&
    echo '"2026.2"' > glslc/src/build-version.inc
}

lankebuild_build() {
    mkdir build && cd build
    cmake -D CMAKE_INSTALL_PREFIX=/usr \
      -D CMAKE_BUILD_TYPE=Release  \
      -D SHADERC_SKIP_TESTS=ON     \
      -G Ninja ..
    ninja -j$(nproc)
    DESTDIR={STAGING_ROOT} ninja install
}

lankebuild_package() {
    :
}
