#!/bin/bash

lankebuild_prepare() {
    # Prepare environment
    :
}

lankebuild_build() {
    ./configure --bindir={BINDIR} --libdir={LIBDIR} --runstatedir=/run --sbindir={SBINDIR} --disable-chfn-chsh --disable-login --disable-nologin --disable-su --disable-setpriv --disable-runuser --disable-pylibmount --disable-liblastlog2 --without-python --without-systemd --disable-static --disable-doc ADJTIME_PATH=/var/lib/hwclock/adjtime
    make -j$(nproc)
    make DESTDIR={STAGING_ROOT} install
    # 添加 Util-linux 兼容性链接
    for arch in x86_64 i386 linux32 linux64 uname26; do
        ln -sfv setarch {STAGING_ROOT}{BINDIR}/$arch
    done
    ln -sfv last {STAGING_ROOT}{BINDIR}/lastb
}


lankebuild_package() {
    # Installation handled by builder
    :
}
