#!/bin/bash

lankebuild_prepare() {
    # Prepare environment
    :
}

lankebuild_build() {
    make PREFIX=/usr SHAREDIR=/usr/share/hwdata SHARED=yes -j$(nproc)
}


lankebuild_package() {
    # Installation handled by builder
    make PREFIX={STAGING_ROOT}/usr SHAREDIR={STAGING_ROOT}/usr/share/hwdata SHARED=yes install
}
