#!/bin/bash

lankebuild_prepare() {
    # Prepare environment
    :
}

lankebuild_build() {
    make PREFIX={PREFIX} SHAREDIR={DATADIR}/hwdata SHARED=yes -j$(nproc)
}


lankebuild_package() {
    # Installation handled by builder
    make PREFIX={STAGING_ROOT}{PREFIX} SHAREDIR={STAGING_ROOT}{DATADIR}/hwdata SHARED=yes install
}
