#!/bin/bash

lankebuild_prepare() {
    # Prepare environment
    :
}

lankebuild_build() {
    mkdir build && cd build
    cmake -DCMAKE_INSTALL_SYSCONFDIR={SYSCONFDIR} -G Ninja .. -DCMAKE_INSTALL_PREFIX={PREFIX} -DCMAKE_BUILD_TYPE=Release -DENABLE_X11=OFF -DCMAKE_INSTALL_LIBDIR=lib -DENABLE_ENCHANT=OFF -Wno-dev
    DESTDIR={STAGING_ROOT} ninja install
}


lankebuild_package() {
    # Installation handled by builder
    install -dm 755 "{STAGING_ROOT}/usr/lib/environment.d"
    cat > "{STAGING_ROOT}/usr/lib/environment.d/fcitx5.conf" << 'EOF'
XMODIFIERS=@im=fcitx
IMSETTINGS_MODULE=fcitx
EOF
}
