#!/bin/bash

lankebuild_prepare() {
    # Prepare environment
    :
}

lankebuild_build() {
    mkdir build && cd build
    cmake -G Ninja .. -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=Release -DENABLE_X11=OFF -DCMAKE_INSTALL_LIBDIR=lib -DENABLE_ENCHANT=OFF
    DESTDIR={STAGING_ROOT} ninja install
}


lankebuild_package() {
    # Installation handled by builder
    mkdir -p "{STAGING_ROOT}/etc/profile.d"
    cat > "{STAGING_ROOT}/etc/profile.d/fcitx5.sh" << 'EOF'
#!/bin/bash
# start of fcitx5
export XMODIFIERS=@im=fcitx
export IMSETTINGS_MODULE=fcitx
# end of fcitx5
EOF
}
