#!/bin/bash

lankebuild_prepare() {
    # Prepare environment
    :
}

lankebuild_build() {
    cargo build --release --bin bindgen
    mkdir -p "{STAGING_ROOT}{BINDIR}"
    cp target/release/bindgen "{STAGING_ROOT}{BINDIR}/"
}


lankebuild_package() {
    # Installation handled by builder
    :
}
