#!/bin/bash

lankebuild_prepare() {
    # Prepare environment
    :
}

lankebuild_build() {
    make BUILD_STATIC=no PREFIX=/usr
    make BUILD_STATIC=no PREFIX=/usr DESTDIR={STAGING_ROOT} install
    # 添加兼容性链接
    ln -sfv lz4 {STAGING_ROOT}/usr/bin/lz4c
    ln -sfv lz4 {STAGING_ROOT}/usr/bin/unlz4
    ln -sfv lz4 {STAGING_ROOT}/usr/bin/lz4cat
}


lankebuild_package() {
    # Installation handled by builder
    :
}
