#!/bin/bash
lankebuild_prepare() {
    :
}
lankebuild_build() {
    mkdir build
    cd build
    meson setup --prefix=/usr ..
    ninja -j$(nproc)
    
    DESTDIR={STAGING_ROOT} ninja install
}
lankebuild_package() {
    :
}
