#!/bin/bash

lankebuild_prepare() {
    # Prepare environment
    :
}

lankebuild_build() {
    ./configure --prefix={PREFIX} --sysconfdir={SYSCONFDIR} --disable-static
    make -j$(nproc)
    make DESTDIR={STAGING_ROOT} install
    ln -sfv texi2any {STAGING_ROOT}{BINDIR}/makeinfo
}


lankebuild_package() {
    # Installation handled by builder
    :
}
