#!/bin/bash

lankebuild_prepare() {
    # Prepare environment
    :
}

lankebuild_build() {
    patch -Np1 -i {SRC_DIR}/coreutils-9.7-i18n-1.patch
    patch -Np1 -i {SRC_DIR}/coreutils-9.7-upstream_fix-1.patch
    autoreconf -fv
    automake -af
    FORCE_UNSAFE_CONFIGURE=1 ./configure --prefix=/usr --disable-static --enable-no-install-program=kill,uptime
    make -j$(nproc)
    make DESTDIR={STAGING_ROOT} install
}


lankebuild_package() {
    # Installation handled by builder
    :
}
