#!/bin/bash

lankebuild_prepare() {
    # Prepare environment
    :
}

lankebuild_build() {
    ./configure --prefix="{PREFIX}" --sysconfdir="{SYSCONFDIR}" --libexecdir="/usr/lib/{PKG_NAME}" --disable-schemas-compile
    make -j$(nproc)
    make DESTDIR="{STAGING_ROOT}" install
}


lankebuild_package() {
    # Installation handled by builder
    :
}
