#!/bin/bash

lankebuild_prepare() {
    # Prepare environment
    :
}

lankebuild_build() {
    tar -xf swaybg-1.2.1.tar.gz
    cd "swaybg-1.2.1"
    meson setup build --prefix={PREFIX} --sysconfdir={SYSCONFDIR} --buildtype=release
    ninja -C build -j$(nproc)
    DESTDIR={STAGING_ROOT} ninja -C build install
}



lankebuild_package() {
    # Installation handled by builder
    :
}
