#!/bin/bash

lankebuild_prepare() {
    ./configure --prefix={PREFIX} --sysconfdir={SYSCONFDIR}
}

lankebuild_build() {
    make -j$(nproc)
}

lankebuild_package() {
    make DESTDIR={STAGING_ROOT} install
}
