#!/bin/bash

lankebuild_prepare() {
    # Prepare environment
    :
}

lankebuild_build() {
    mkdir build && cd build
    meson setup .. --prefix=/usr --buildtype=release -Dplatforms=wayland -Dgallium-drivers=iris,nouveau,radeonsi,llvmpipe,zink -Dvulkan-drivers=intel,amd,swrast -Degl=enabled -Dgbm=enabled -Dglx=disabled -Dgles1=enabled -Dgles2=enabled -Dglvnd=enabled -Dllvm=enabled -Dshared-llvm=enabled -Dvalgrind=disabled -Dlibunwind=disabled -Dvideo-codecs=all -Dspirv-tools=enabled -Dbuild-tests=false -Dcpp_rtti=false
    DESTDIR={STAGING_ROOT} ninja install
}


lankebuild_package() {
    # Installation handled by builder
    :
}
