#!/bin/bash

lankebuild_prepare() {
    # Prepare environment
    :
}

lankebuild_build() {
    ./gitcompile --prefix=/usr --disable-python --with-configdir=/usr/share/alsa --with-alsagconfdir=/etc/alsa/conf.d
    make
    make DESTDIR={STAGING_ROOT} install
}


lankebuild_package() {
    # Installation handled by builder
    :
}
