#!/bin/bash

lankebuild_prepare() {
    # Prepare environment
    :
}

lankebuild_build() {
    mkdir build && cd build
    cmake -DCMAKE_INSTALL_SYSCONFDIR={SYSCONFDIR} -G Ninja .. -DCMAKE_INSTALL_PREFIX={PREFIX} -DBUILD_HTML_DOCS=OFF -DBUILD_MAN_DOCS=OFF
    DESTDIR={STAGING_ROOT} ninja install
}


lankebuild_package() {
    # Installation handled by builder
    :
}
