#!/bin/bash

lankebuild_prepare() {
    # Prepare environment
    :
}

lankebuild_build() {
    ./configure --prefix={PREFIX} --sysconfdir={SYSCONFDIR} --disable-static --disable-doc
    make -j$(nproc)
    make DESTDIR={STAGING_ROOT} install
    ln -sfv flex {STAGING_ROOT}{BINDIR}/lex
    ln -sfv flex {STAGING_ROOT}{BINDIR}/flex++
}


lankebuild_package() {
    # Installation handled by builder
    :
}
