#!/bin/bash

lankebuild_prepare() {
    # Prepare environment
    :
}

lankebuild_build() {
    mkdir build && cd build
    cmake -DCMAKE_INSTALL_SYSCONFDIR={SYSCONFDIR} -G Ninja .. -DCMAKE_INSTALL_PREFIX={PREFIX} -DCMAKE_BUILD_TYPE=Release -DENABLE_GUI=OFF -DENABLE_QT=OFF -DENABLE_OPENCC=OFF -DCMAKE_INSTALL_LIBDIR=lib
    DESTDIR={STAGING_ROOT} ninja install
}


lankebuild_package() {
    # Installation handled by builder
    :
}
