#!/bin/bash

lankebuild_prepare() {
    # Prepare environment
    :
}

lankebuild_build() {
    cmake -B build -G Ninja -DCMAKE_INSTALL_PREFIX=/usr -DBUILD_WSI_XCB_SUPPORT=ON -DBUILD_WSI_XLIB_SUPPORT=ON -DBUILD_WSI_WAYLAND_SUPPORT=ON -D CMAKE_SKIP_INSTALL_RPATH=ON
    cmake --build build
    DESTDIR={STAGING_ROOT} cmake --install build
}


lankebuild_package() {
    # Installation handled by builder
    :
}
