#!/bin/sh
set -e

lankebuild_prepare() {
    mkdir -p build
}

lankebuild_build() {
    echo "Configuring libgudev-238..."
    cd build
    meson setup .. --prefix={PREFIX} --sysconfdir={SYSCONFDIR} --buildtype=release
    echo "Building libgudev-238..."
    ninja -j$(nproc)
    echo "Build complete."
}

lankebuild_package() {
    echo "Packaging libgudev-238..."
    cd build
    DESTDIR="{STAGING_ROOT}" ninja install
    echo "Package staging complete."
}
