#!/bin/bash

lankebuild_prepare() {
    :
}

lankebuild_build() {
    ./configure --prefix={PREFIX} --sysconfdir={SYSCONFDIR} \
        --enable-shared \
        --disable-static \
        --enable-threads \
        --enable-sse2 \
        --enable-avx2
    make -j$(nproc)
    make DESTDIR={STAGING_ROOT} install
}

lankebuild_package() {
    :
}
