#!/bin/bash

lankebuild_prepare() {
    # 使用自定义配置，启用共享库
    ./configure --prefix={PREFIX} --sysconfdir={SYSCONFDIR} \
                --enable-shared
}

lankebuild_build() {
    make -j$(nproc)
    make DESTDIR={STAGING_ROOT} install
}

lankebuild_package() {
    :
}
