#!/bin/bash

lankebuild_prepare() {
    # Prepare environment
    :
}

lankebuild_build() {
    make NETNS_RUN_DIR=/run/netns -j$(nproc)
    make SBINDIR={SBINDIR} DESTDIR={STAGING_ROOT} install
    ln -sfv lnstat {STAGING_ROOT}{BINDIR}/ctstat
    ln -sfv lnstat {STAGING_ROOT}{BINDIR}/rtstat
}


lankebuild_package() {
    # Installation handled by builder
    :
}
