#!/bin/bash

lankebuild_prepare() {
    # Prepare environment
    :
}

lankebuild_build() {
    gcc -shared -fPIC -O2 -o libduktape.so.2.7.0 src/duktape.c -lm
    mkdir -p {STAGING_ROOT}/usr/include {STAGING_ROOT}/usr/lib/pkgconfig
    cp -v src/duktape.h src/duk_config.h src/duk_util.h {STAGING_ROOT}/usr/include/
    cp -v libduktape.so.2.7.0 {STAGING_ROOT}/usr/lib/
    ln -sf libduktape.so.2.7.0 {STAGING_ROOT}/usr/lib/libduktape.so
    cat > {STAGING_ROOT}/usr/lib/pkgconfig/duktape.pc << EOF
prefix=/usr
libdir=\$prefix/lib
includedir=\$prefix/include
Name: duktape
Description: Duktape engine
Version: 2.7.0
Libs: -L\$libdir -lduktape -lm
Cflags: -I\$includedir
EOF
}


lankebuild_package() {
    # Installation handled by builder
    :
}
