#!/bin/bash

lankebuild_prepare() {
    # Prepare environment
    :
}

lankebuild_build() {
    sed -i 's/-Os/-O2/' Makefile.sharedlibrary
    make -f Makefile.sharedlibrary INSTALL_PREFIX=/usr -j$(nproc)
    make -f Makefile.sharedlibrary INSTALL_PREFIX=/usr DESTDIR={STAGING_ROOT} install
    mkdir -p {STAGING_ROOT}{LIBDIR}/pkgconfig
    cat > {STAGING_ROOT}{LIBDIR}/pkgconfig/duktape.pc << 'EOF'
prefix=/usr
libdir=$prefix/lib
includedir=$prefix/include
Name: duktape
Description: Duktape engine
Version: 2.7.0
Libs: -L$libdir -lduktape -lm
Cflags: -I$includedir
EOF
}


lankebuild_package() {
    # Installation handled by builder
    :
}
