#!/bin/bash

lankebuild_prepare() {
    # Prepare environment
    :
}

lankebuild_build() {
    meson setup build --prefix=/usr -Dxcb=disabled -Dxlib=disabled
    DESTDIR={STAGING_ROOT} ninja -C build install
}


lankebuild_package() {
    # Installation handled by builder
    :
}
