#!/bin/bash

lankebuild_prepare() {
    # Prepare environment
    :
}

lankebuild_build() {
    ./configure --prefix=/usr --libexecdir=/usr/lib --with-secure-path --with-all-insults --with-env-editor --disable-static --disable-doc
    make -j$(nproc)
    make DESTDIR={STAGING_ROOT} install
    ln -sfv sudo {STAGING_ROOT}/usr/bin/sudoedit
}

lankebuild_package() {
    # Installation handled by builder
    :
}
