#!/bin/bash
lankebuild_prepare() {
    :
}
lankebuild_build() {
    ./configure --prefix=/usr --disable-static
    make -j$(nproc)
    make DESTDIR={STAGING_ROOT} install
}
lankebuild_package() {
    :
}
