#!/bin/bash

lankebuild_prepare() {
    # Prepare environment
    :
}

lankebuild_build() {
    ./configure --prefix=/usr --sysconfdir=/etc --disable-static --disable-doc --disable-setuid --enable-cache-owner=bin
    make -j$(nproc)
    make DESTDIR={STAGING_ROOT} install
}


lankebuild_package() {
    # Installation handled by builder
    :
}
